### ISSUE TITLE
TraceView doesn't seem to show URLs for Chromium events?

### ISSUE THREAD

**Issue by ericlaw1979** [microsoft/MSO-Scripts#12] opened 2024-10-02 18:10 UTC
Is this expected?

![image](https://github.com/user-attachments/assets/5c1bfe0a-676f-4f68-9e7d-588ed6060a5b)

**Comment by rayfo** [comment] 2024-10-04 09:44
**Short Story**
This is by design, but the options to see the URLs for Edge/Chrome could/will be better documented.
The WPA add-in to view network activity works with TCP/IP, WinSock, WinHTTP/WebIO, WinINet (which most Windows apps use), but not the Chromium ETW ... which can be viewed in other ways.
The underlying network layers TCP/IP and WinSock do not reveal URLs. (And UDP traffic does not have URLs.)
See the wiki: (https://github.com/microsoft/MSO-Scripts/wiki/Network-Activity#chromium)

**Long Story**
When developing the WPA Network add-in ("NetBlame"), we looked very closely at the ETW events emitted by Chromium (Chrome/Edge/WebView2), but they unfortunately cannot be correlated.  Therefore, only the underlying TCP/IP and WinSock activity appears for MSEdge.exe and Chrome.exe, etc. ... which does not contain URL info.

But the Chromium URLs can be exposed:
1. Using `TraceNetwork View`, see the Chromium Events tab, which reveals Chromium events by way of [WPA's Regions of Interest mechanism](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/regions-of-interest).
2. Try the experimental script: `BETA\TraceEdgeChrome` with the usual commands: Start / Stop / View / Status / Cancel / -?
  (This script captures a different set of ETW events.)
    * In the Generic Events graph/table, find the URL annotation (Annotations column).
    * The Regions of Interest graph/table pairs most Chromium ETW events to chart how long they take to execute.
3. Using a trace created using TraceNetwork, you can see an alternate view using TraceEdgeChrome:
    `BETA\TraceEdgeChrome View -Path $Env:LocalAppData\MSO-Scripts\MSO-Trace-Network.etl`

Does that help?

_I'll update the wiki and then close this issue._

**Comment by rayfo** [comment] 2024-10-07 12:13
* I have updated the wiki to better explain how to analyze a Chromium browser trace.
  https://github.com/microsoft/MSO-Scripts/wiki/Network-Activity#chromium
* I have a modest improvement for BETA/WPAP/MSEdge.wpaProfile which I will push soon.

**Comment by rayfo** [comment] 2024-10-07 12:20
Hey Eric, thanks for trying out MSO-Scripts.
I've updated the wiki to explain how to trace Chromium browsers.
https://github.com/microsoft/MSO-Scripts/wiki/Network-Activity#chromium
Do let me know if this is helpful, and I'll close Issue #12<https://github.com/microsoft/MSO-Scripts/issues/12>.
Raymond Fowkes
________________________________
From: Eric Lawrence ***@***.***>
Sent: Wednesday, October 2, 2024 11:11 AM
To: microsoft/MSO-Scripts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [microsoft/MSO-Scripts] TraceView doesn't seem to show URLs for Chromium events? (Issue #12)


Is this expected?

image.png (view on web)<https://github.com/user-attachments/assets/5c1bfe0a-676f-4f68-9e7d-588ed6060a5b>

**Closed** 2024-10-17 17:33 UTC
